spring:
  profiles:
    active:
      - devOne
---
server:
  port: 9001
eureka:
  instance: # eureak实例定义
    hostname: Eureka-One # 定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:eureka@Eureka-One:9001/eureka,http://admin:eureka@Eureka-Two:9002/eureka,http://admin:eureka@Eureka-Three:9003/eureka

spring:
  profiles: devOne
  security:
    user:
      name: admin
      password: eureka
---
server:
  port: 9002
eureka:
  instance: # eureak实例定义
    hostname: Eureka-Two # 定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:eureka@Eureka-One:9001/eureka,http://admin:eureka@Eureka-Two:9002/eureka,http://admin:eureka@Eureka-Three:9003/eureka

spring:
  profiles: devTwo
  security:
    user:
      name: admin
      password: eureka
---
server:
  port: 9003
eureka:
  instance: # eureak实例定义
    hostname: Eureka-Three # 定义 Eureka 实例所在的主机名称
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:eureka@Eureka-One:9001/eureka,http://admin:eureka@Eureka-Two:9002/eureka,http://admin:eureka@Eureka-Three:9003/eureka

spring:
  profiles: devThree
  security:
    user:
      name: admin
      password: eureka






